### ISSUE TITLE
Regarding tiC output in a Plumed like file

### ISSUE THREAD

**Issue by sbhakat** [msultan/tica_metadynamics_paper_1#2] opened 2018-02-14 12:46 UTC
Dear Developer,

I used tica_metadynamics.plumed_writer to render tiC in a Plumed like file. I am using distance between CA of 35--79 and 215--293 during featurization extract. My only doubt is `meanfree_None_CA` a Plumed keyword? I didn't find any keyword related to `meanfree_None_CA` in Plumed v2.4.

Will the argument be simple distance between these CA residues?

> `COMBINE` LABEL=tic0 ARG=meanfree_None_CA_35_79,meanfree_None_CA_215_293 COEFFICIENTS=-2.79596065984,0.937056752171 PERIODIC=NO`

**Comment by msultan** [comment] 2018-02-14 13:46
Thats just the label for the ca distances to reference the distance which is calculated above. The label can be anything but i tried to make it as humanly understandable (to me at least) as possible. 

meanfree_None_CA_35_79 is the _meanfree_ CA distance between residues 35 and 79. The mean transform is necessary for tiCA and is done internally by our MSMBuilder code but has to be done explicitly here. FYI, I have simplified the naming scheme in the new versions of the code but it does the same thing though

If you are using MSMBuilders' contact featurizer and tica model the following script should work for you. 

``` python
from msmbuilder.featurizer import ContactFeaturizer
import pandas as pd 
from tica_metadynamics.plumed_writer import render_tica_plumed_file

feat =ContactFeaturizer([[35,79],[215,293]], scheme='ca')

top = mdtraj.load("./example_top.pdb")
# This defines a pandas dataframe which tells us how each contact is calculated. i.e. what atom indices are involved etc. 
df =pd.DataFrame(feat.describe_features(top))

# going up to two tICs for example
tica_model = tICA(n_components=2)

# Your code for fitting the tICA model to existing trajectories. 



# to generate the plumed files 

output  = render_tica_plumed_file(tica_mdl =tica_model, df=df, n_tics=2)

# output is a dictionary whose integer values are the tICs
# to get the 0th tIC
print(output[0])

# to get the 1st tIC
print(output[1])

```

The output should be similar but NOT exactly like the file below: 
https://github.com/msultan/vde_metadynamics/blob/master/examples/ww_domain/fip_plumed.dat


I would also recommend comparing the output from ```plumed driver``` against the MSMbuilder output to ensure everything went smoothly. They are equal to 3-4 decimal places at least. 

lemme know if you have any issues.

**Comment by sbhakat** [comment] 2018-02-14 16:53
I got an error like following while executing  
`output`  = render_tica_plumed_file(tica_mdl =tica_model, df=df, `n_tics=2)`

Error is following:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-118-6534a83ca32b> in <module>()
----> 1 output  = render_tica_plumed_file(tica_mdl= 'tica_model', df= 'df1', n_tics= '2')

/home/sbhakat/miniconda2/envs/newenv/lib/python3.4/site-packages/tica_metadynamics-0.1-py3.4.egg/tica_metadynamics/plumed_writer.py in render_tica_plumed_file(tica_mdl, df, n_tics, grid_list, interval_list, wall_list, nrm, pace, height, biasfactor, temp, sigma, stride, hills_file, bias_file, label, walker_n, walker_id, **kwargs)
    403     if interval_list is None:
    404         interval_list = np.repeat(None, n_tics)
--> 405     multiple_tics = kwargs.pop('multiple_tics')
    406     if type(multiple_tics) == int:
    407         output = []

KeyError: 'multiple_tics'

Any solution?

**Comment by sbhakat** [comment] 2018-02-14 16:54
Also what you mean by

Your code for fitting the tICA model to existing trajectories. 

Do you have any example for that?

**Comment by msultan** [comment] 2018-02-14 16:56
try this instead. 
```render_tica_plumed_file(tica_mdl= tica_model, df= df1, n_tics= 2,multiple_tics=None)```
fyi mutiple_tics allows for multi dimensional (2D tic 0 and tic 1 instead of two 1D tics) sampling.

**Comment by msultan** [comment] 2018-02-14 16:57
>Your code for fitting the tICA model to existing trajectories.

try the following:
```python
traj_list = glob.glob("*.xtc")
trajs = [md.load(i, top=top) for i in traj_list]
features = feat.transform(trajs)
tica_features = tica_model.fit_transform(features)
```

the tICA model is now fit to existing simulations. It will find the slowest set of coordinates in them and then you can sample that process again to get better statistics. For some systems, you dont need to observe a cross-over trajectory to be able to approximate the general tICA model.

**Comment by msultan** [comment] 2018-02-14 17:04
> output = render_tica_plumed_file(tica_mdl= 'tica_model', df= 'df1', n_tics= '2')

ps the ```tica_model``` should **not** be in quotes. That actually is a string in python where as what we want is the MSMBuilder tICA class object.  Similarly for the dataframe(df1) too

**Comment by sbhakat** [comment] 2018-02-14 17:16
This looks like a numpy array problem

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-128-35bb4f75083e> in <module>()
----> 1 output  = render_tica_plumed_file(tica_mdl= tica_model, df= df1, n_tics= 2, multiple_tics= None)

/home/sbhakat/miniconda2/envs/newenv/lib/python3.4/site-packages/tica_metadynamics-0.1-py3.4.egg/tica_metadynamics/plumed_writer.py in render_tica_plumed_file(tica_mdl, df, n_tics, grid_list, interval_list, wall_list, nrm, pace, height, biasfactor, temp, sigma, stride, hills_file, bias_file, label, walker_n, walker_id, **kwargs)
    448         output.append("RESTART\n")
    449         inds = np.nonzero(tica_mdl.components_[i,:])[0]
--> 450         raw_feats = render_raw_features(df, inds)
    451         mean_feats = render_mean_free_features(df, inds, tica_mdl, nrm)
    452         output.append(raw_feats)

/home/sbhakat/miniconda2/envs/newenv/lib/python3.4/site-packages/tica_metadynamics-0.1-py3.4.egg/tica_metadynamics/plumed_writer.py in render_raw_features(df, inds)
    175                 output.append(func("../pdbs/%d.pdb"%feature_index , feat_label))
    176             elif  df.featurizer[feature_index] == "Contact" and len(df.atominds[feature_index][0])==1:
--> 177                 output.append(func(inds=[np.array(atominds[0][0])+1,
    178                                          np.array(atominds[1][0])+1],
    179                                    label=feat_label))

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')

**Comment by sbhakat** [comment] 2018-02-14 17:17
If I do this
`render_tica_plumed_file(tica_mdl= tica_model, df= df1, n_tics= 2,multiple_tics=2)`

I get the error
Running Multiple tics per simulation. Going up to tic index 2

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-130-1ea18ac75362> in <module>()
----> 1 render_tica_plumed_file(tica_mdl= tica_model, df= df1, n_tics= 2, multiple_tics=2)

/home/sbhakat/miniconda2/envs/newenv/lib/python3.4/site-packages/tica_metadynamics-0.1-py3.4.egg/tica_metadynamics/plumed_writer.py in render_tica_plumed_file(tica_mdl, df, n_tics, grid_list, interval_list, wall_list, nrm, pace, height, biasfactor, temp, sigma, stride, hills_file, bias_file, label, walker_n, walker_id, **kwargs)
    409         print("Running Multiple tics per simulation. Going up to tic index %d"%n_tics)
    410         inds = np.unique(np.nonzero(tica_mdl.components_[:multiple_tics,:])[1])
--> 411         raw_feats = render_raw_features(df, inds)
    412         mean_feats = render_mean_free_features(df, inds, tica_mdl, nrm)
    413         output.append(raw_feats)

/home/sbhakat/miniconda2/envs/newenv/lib/python3.4/site-packages/tica_metadynamics-0.1-py3.4.egg/tica_metadynamics/plumed_writer.py in render_raw_features(df, inds)
    175                 output.append(func("../pdbs/%d.pdb"%feature_index , feat_label))
    176             elif  df.featurizer[feature_index] == "Contact" and len(df.atominds[feature_index][0])==1:
--> 177                 output.append(func(inds=[np.array(atominds[0][0])+1,
    178                                          np.array(atominds[1][0])+1],
    179                                    label=feat_label))

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')

**Comment by msultan** [comment] 2018-02-14 17:37
can you get the ouput of what df1 looks looks like 
```
print(df1)
```

**Comment by msultan** [comment] 2018-02-14 17:38
also, unless you want multi-dimensional gaussians, its best to set ```multiple_tics=None```

**Comment by sbhakat** [comment] 2018-02-14 17:39
printing df1 looks something like following         

`atominds featuregroup featurizer otherinfo      resids    resnames  \
0  [[N/A], [N/A]]           CA    Contact        20    [35, 79]  [ASP, VAL]   
1  [[N/A], [N/A]]           CA    Contact        20  [215, 293]  [ASH, LEU]   

      resseqs  
0    [36, 80]  
1  [216, 294]`

**Comment by msultan** [comment] 2018-02-14 17:41
ahh, i know whats happening. I think its a upper lower case issue. That is definitely on me. 

```python 
#note the capital CA
feat =ContactFeaturizer([[35,79],[215,293]], scheme='CA')
df =pd.DataFrame(feat.describe_features(top))
print(df)
```
This should have actual 0-indexed atom indices in the atom inds column.

**Comment by sbhakat** [comment] 2018-02-14 17:47
Well it was always capital from the beginning

`swap this for whatever you have. The code for now supports contacts, dihedral, and angles. `
feat =ContactFeaturizer([[35,79],[215,293]], scheme='CA')`

**Comment by msultan** [comment] 2018-02-14 18:03
can you try the inverse then i.e scheme='ca'?

**Comment by sbhakat** [comment] 2018-02-14 18:07
It didn't make any change.

**Comment by sbhakat** [comment] 2018-02-14 18:09
It definitely looks like this kind of error https://stackoverflow.com/questions/35013726/typeerror-ufunc-add-did-not-contain-a-loop-with-signature-matching-types/35016330

**Comment by msultan** [comment] 2018-02-14 18:14
hmm, there is something with the featurizer for sure. what version of msmbuilder do you have? On ver 3.9, i get the following for one of my topologies. 
``` python
feat =ContactFeaturizer([[35,79],[35,68]], scheme='ca')
pd.DataFrame(feat.describe_features(traj))

  | atominds | featuregroup | featurizer | otherinfo | resids | resnames | resseqs
-- | -- | -- | -- | -- | -- | -- | --
[[582], [1302]] | ca | Contact | 20 | [35, 79] | [ALA, ILE] | [36, 80]
[[582], [1127]] | ca | Contact | 20 | [35, 68] | [ALA, LEU] | [36, 69]

```

**Comment by sbhakat** [comment] 2018-02-14 18:25
How can one change the version?

**Comment by msultan** [comment] 2018-02-14 18:26
check the version using . we are currently on version 3.9+ i believe. 
``` 
import msmbuilder as msmb
print(msmb.version.full_version)
```
then install using pip + github.

**Comment by sbhakat** [comment] 2018-02-14 18:28
Is it possible to resolve this issue with current version? Is your topology file only contains CA or all atoms?

**Comment by msultan** [comment] 2018-02-14 18:29
nope, my topology is all atoms.

**Comment by sbhakat** [comment] 2018-02-14 18:30
Okay I will try by changing topology but I guess that will not make any big change.

**Comment by msultan** [comment] 2018-02-14 18:32
can you print the following . it might be that mdtraj cant find the CA atoms though i have my doubts there. 

```
print([i.index for i in traj.top.atoms if i.name=='CA'])
```

**Comment by msultan** [comment] 2018-02-14 18:33
The dataframe is populated from this line so i dont see any obvious problem here unless you want to share the toplogy. 
https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/featurizer/featurizer.py#L1206

**Comment by msultan** [comment] 2018-02-15 01:41
@sbhakat did you get this to work?

**Comment by sbhakat** [comment] 2018-02-15 09:39
No. Here is the link containing my trajectory and topology file. Could you please see the problem. Otherwise I have to install 3.9 dev version but this seems to me a easy problem to solve. 

https://www.dropbox.com/sh/dl97mcf4qku42f4/AADsFxus8AaXzR4Z8_VbcDfMa?dl=0

**Comment by sbhakat** [comment] 2018-02-15 10:21
How you print CA from data. I think my command (following) is wrong

`trajs = md.load('../tfit.xtc', top='../prot0.pdb')`
`ds = dataset("../tfit.xtc", topology='../prot0.pdb')`
`print(topology.select('name CA'))`

I am getting an error like this

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-214-9a9534a903cf> in <module>()
      1 trajs = md.load('../tfit.xtc', top='../prot0.pdb')
      2 ds = dataset("../tfit.xtc", topology='../prot0.pdb')
----> 3 print(topology.select('name CA'))

NameError: name 'topology' is not defined

**Comment by sbhakat** [comment] 2018-02-15 11:14
I definitely think that MDTraj is not recognising my xtc and pdb files

I used a command like following

`trajectory_folder_path=("../tfit.xtc")`
`t = md.load_xtc('../tfit.xtc', top='../prot0.pdb')`
`ds = dataset("../tfit.xtc", topology='../prot0.pdb')`

`#get some stats about the dataset`
`print("Number of trajectories is %d"%len(ds))`
`print("How many residues? %d"%len(ds))`
`print("How many atoms? %d"%len(ds))`

The output is 

Number of trajectories is 1
How many residues? 1
How many atoms? 1

It can't be 1 residues and 1 atoms thats for sure

I am not sure where I am doing wrong

**Comment by sbhakat** [comment] 2018-02-15 11:22
I think this is due to the .pdb file which can be found here https://www.dropbox.com/sh/dl97mcf4qku42f4/AADsFxus8AaXzR4Z8_VbcDfMa?dl=0

Is it due to the AMBER naming of HIS to HIE/HID/HIP ?

**Comment by sbhakat** [comment] 2018-02-15 13:33
I also added a .html version of my notebook so that you can see what commands I am doing wrong.

**Comment by msultan** [comment] 2018-02-15 15:09
yep, this is a msmbuilder version issue. I can get it to work,using the original code, on ver 3.8+. Could you try upgrading your msmbuilder version? 


In the meanwhile, here is the output i am getting on my machine. 

https://www.dropbox.com/s/a8ovogas9n5cygw/df.pkl?dl=0

To load it 
```python
from msmbuilder.utils import load

df = load("./df.pkl")

print(df)

```
      
```python
 atominds featuregroup featurizer otherinfo      resids    resnames  \
0   [[534], [1203]]           ca    Contact        20    [35, 79]  [ASP, VAL]   
1  [[3336], [4558]]           ca    Contact        20  [215, 293]  [ASH, LEU]   

      resseqs  
0    [36, 80]  
1  [216, 294]  
```

Also, i know mdtraj used to have some issues with the ASH residue but i think it was fixed since my local branch it seems to be able to pick up the residue just fine.

**Comment by sbhakat** [comment] 2018-02-15 15:38
How can one upgrade it to 3.8+?

**Comment by msultan** [comment] 2018-02-15 18:06
Please follow the instructions on the website: http://msmbuilder.org/3.8.0/

In short, the following bash command should do it. 
``` bash
conda install -c omnia msmbuilder
```

If you dont have conda, git clone the msmbuilder master branch and then run the following in the msmbuilder folder. 

``` bash
python setup.py install
````

**Comment by sbhakat** [comment] 2018-02-15 18:16
It is already installed

`Fetching package metadata ...............`
`Solving package specifications: .`

`# All requested packages already installed.`
`# packages in environment at /home/sbhakat/miniconda2/envs/newenv:`
`#`
`msmbuilder                3.8.0               np111py34_0    omnia`

**Comment by msultan** [comment] 2018-02-15 18:21
hmm, i dont know how that is happening since i cant reproduce that bug on my machine. Try to make sure that there arn't multiple copies of msmbuilder in your system.

**Comment by sbhakat** [comment] 2018-02-15 18:27
Well there seems to be multiple copies of msmb

./miniconda2/pkgs/msmbuilder-3.8.0-np112py27_0/lib/python2.7/site-packages/msmbuilder/msm
./miniconda2/pkgs/msmbuilder-3.8.0-np112py27_0/lib/python2.7/site-packages/msmbuilder/project_templates/msm
./miniconda2/pkgs/msmbuilder-3.8.0-np111py34_0/lib/python3.4/site-packages/msmbuilder/msm
./miniconda2/pkgs/msmbuilder-3.8.0-np111py34_0/lib/python3.4/site-packages/msmbuilder/project_templates/msm
./miniconda2/lib/python2.7/site-packages/msmbuilder/msm
./miniconda2/lib/python2.7/site-packages/msmbuilder/project_templates/msm
./miniconda2/envs/newenv/lib/python3.4/site-packages/msmbuilder/msm
./miniconda2/envs/newenv/lib/python3.4/site-packages/msmbuilder/project_templates/msm


So now the question how to un-install msmb?

**Comment by msultan** [comment] 2018-02-15 18:28
conda remove should work. do it a bunch of times until all of them go away, and then do a clean install.

**Comment by sbhakat** [comment] 2018-02-15 18:38
This is getting out of hand.
I reinstalled msmb builder and executed the following command

trajectory_folder_path=("../tfit.xtc")
t = md.load_xtc('../tfit.xtc', top='../prot0.pdb')
ds = dataset("../tfit.xtc", topology='../prot0.pdb')

#get some stats about the dataset
print("Number of trajectories is %d"%len(ds))
print("How many residues? %d"%len(ds))
print("How many atoms? %d"%len(ds))

It is still showing

Number of trajectories is 1
How many residues? 1
How many atoms? 1

This is impossible

**Comment by sbhakat** [comment] 2018-02-15 18:52
So I think we can say the current version available in internet has some problem in recognising a .xtc and corresponding .pdb file. Seems like so.

**Comment by msultan** [comment] 2018-02-15 19:02
```python
print("Number of trajectories is %d"%len(ds))
print("How many residues? %d"%len(ds))
print("How many atoms? %d"%len(ds))

```
The dataset object has no information about the residues or atoms so it shouldnt know how many atoms or residues there are. It is simply designed to automate the transforming and fitting of trajectories.

**Comment by msultan** [comment] 2018-02-15 19:02
with the new code, can you follow the original instructions to get the dataframe?

**Comment by sbhakat** [comment] 2018-02-15 19:23
You mean with msm3.9

Is the following an issue?

I have default python 2.7 installed using Anaconda

Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) 

But when I installed msmbuilder I activated a new python environment with Python 3.4 and installed it with Python 3.4 enviornment.

Will that be an issue?

**Comment by msultan** [comment] 2018-02-15 19:24
no, i have python 3.4+, just use the code from the top of the page.

**Comment by sbhakat** [comment] 2018-02-15 19:25
You mean this code

print([i.index for i in traj.top.atoms if i.name=='CA'])

**Comment by msultan** [comment] 2018-02-15 19:26
this one
```feat =ContactFeaturizer([[35,79],[215,293]], scheme='ca')
df =pd.DataFrame(feat.describe_features(top))
print(df)
```

**Comment by sbhakat** [comment] 2018-02-15 19:34
Wow this seems working Great :)

           atominds featuregroup featurizer otherinfo      resids    resnames  \
0   [[534], [1203]]           ca    Contact        20    [35, 79]  [ASP, VAL]   
1  [[3336], [4558]]           ca    Contact        20  [215, 293]  [ASH, LEU]   

      resseqs  
0    [36, 80]  
1  [216, 294]

**Comment by msultan** [comment] 2018-02-15 19:35
Great, hopefully now the  tica_plumed scripts can work too.

**Comment by sbhakat** [comment] 2018-02-15 19:35
This seems like giving the output. Does this looks reasonable

{0: 'RESTART\nDISTANCE ATOMS=535,1204 LABEL=ca_35_79 \n\nDISTANCE ATOMS=3337,4559 LABEL=ca_215_293 \n\nMATHEVAL ARG=ca_35_79 FUNC=x-1.50598185555 LABEL=meanfree_None_ca_35_79 PERIODIC=NO \n\nMATHEVAL ARG=ca_215_293 FUNC=x-1.49390354372 LABEL=meanfree_None_ca_215_293 PERIODIC=NO \n\nCOMBINE LABEL=tic0 ARG=meanfree_None_ca_35_79,meanfree_None_ca_215_293 COEFFICIENTS=-2.79596065984,0.937056752171 PERIODIC=NO \nMETAD ARG=tic0 SIGMA=0.2 HEIGHT=1.0 FILE=HILLS TEMP=300 PACE=1000 LABEL=metad BIASFACTOR=50\nPRINT ARG=tic0,metad.bias STRIDE=1000 FILE=BIAS ', 1: 'RESTART\nDISTANCE ATOMS=535,1204 LABEL=ca_35_79 \n\nDISTANCE ATOMS=3337,4559 LABEL=ca_215_293 \n\nMATHEVAL ARG=ca_35_79 FUNC=x-1.50598185555 LABEL=meanfree_None_ca_35_79 PERIODIC=NO \n\nMATHEVAL ARG=ca_215_293 FUNC=x-1.49390354372 LABEL=meanfree_None_ca_215_293 PERIODIC=NO \n\nCOMBINE LABEL=tic1 ARG=meanfree_None_ca_35_79,meanfree_None_ca_215_293 COEFFICIENTS=-0.348378998352,-11.6585651295 PERIODIC=NO \nMETAD ARG=tic1 SIGMA=0.2 HEIGHT=1.0 FILE=HILLS TEMP=300 PACE=1000 LABEL=metad BIASFACTOR=50\nPRINT ARG=tic1,metad.bias STRIDE=1000 FILE=BIAS '}

**Comment by msultan** [comment] 2018-02-15 19:37
yep, that should be it
```# to generate the plumed files 

output  = render_tica_plumed_file(tica_mdl =tica_model, df=df, n_tics=2)

# output is a dictionary whose integer values are the tICs
# to get the 0th tIC
print(output[0])

# to get the 1st tIC
print(output[1])
```

**Comment by msultan** [comment] 2018-02-15 19:39
oh as a sanity check, you can compare a topology using the plumed script above  and the msmbuilder using the following 
Do the following in bash
```bash
plumed driver --mf_pdb 0.pdb --plumed plumed.dat
```
and the following in python
``` 
traj = [md.load("0.pdb")]
print(tica_model.transform(feat.transform(traj)))

```
they should be exactly equal to 3-4 decimal points. you will probably need to hack the plumed script to ouput the values to a file though.

**Comment by sbhakat** [comment] 2018-02-15 19:40
Great, awesome. Thanks a million. I will confirm it for sure

**Comment by sbhakat** [comment] 2018-02-15 19:55
Nice. In Plumed

#! FIELDS time tic1
 0.000000 0.651439

#! FIELDS time tic0
 0.000000 -0.410350

Whereas in python

[array([[-0.4103521 ,  0.65144574]])]

Thats great

**Comment by msultan** [comment] 2018-02-15 20:01
Awesome, have fun running those simulations.

**Comment by sbhakat** [comment] 2018-02-15 20:02
Million thanks. I will get back with more questions. Thanks again

**Comment by sbhakat** [comment] 2018-02-16 16:23
Quick question again: How much I can trust the biasfactor mentioned in the rendered Plumed file?

**Comment by msultan** [comment] 2018-02-16 16:25
Oh, you should change that if its too high for you. its a random number I picked when i developed this package early on. From the plumed folks, it seems like 10-20 should be "good" enough to sample every millisecond timescale process but of course that depends on how good the CV is

**Comment by sbhakat** [comment] 2018-02-16 16:25
Great Thanks a lot

**Comment by sbhakat** [comment] 2018-02-19 14:00
Hi, Question once more.

I am happy with tICA but I wanted to do kPCA and t SNE analysis on the same dataset. It must be pretty easy I guess.

I tried the following

`from sklearn.decomposition import KernelPCA`

`kpca = KernelPCA(n_components=2, kernel="linear")`
`kpca_features = ds_contact.kpca.fit_transform(kpca_mdl, out_ds = 'reg_kpcas_2comp//')`

It gives an error like following

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-5157465a2868> in <module>()
      1 kpca = KernelPCA(n_components=2, kernel="linear")
----> 2 kpca_features = ds_contact.kpca.fit_transform(kpca_mdl, out_ds = 'reg_kpcas_2comp//')

AttributeError: 'NumpyDirDataset' object has no attribute 'kpca'

Do you have any idea what is happening?

**Comment by msultan** [comment] 2018-02-19 14:32
```
kpca_features = ds_contact.kpca.fit_transform(kpca_mdl, out_ds = 'reg_kpcas_2comp//')
```
That seems wrong. The ```.kpca``` seems extra. 
Also, i dont think SKlearn objects will directly work out of the box with MSMBuilder. They are highly compatible, and we borrow them a lot. However, we tend to work with a lot of various sized MD trajectories so our data sets are M,X,N( trajectories, datapoints, features) while the SKLearn datasets are usually X,N ( datapoints, features). That also might or might not be an issue. You might want to check out the PCA object from ```msmbuilder.decomposition``` and its parent class ```MultiSequenceDecompositionMixin``` to see how we end up solving this issue.

**Comment by msultan** [comment] 2018-10-02 16:53
closing now.

**Closed as completed by msultan** 2018-10-02 16:53 UTC
